#!/usr/bin/env bash
# This script configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
apt-get update
apt-get -y install nginx
echo "http { server { listen 80; location / { return 200 "Hello World!"; } } }" >> /etc/nginx/nginx.conf
service nginx start
