#!/usr/bin/env bash
# This script automatically configure a Ubuntu machine to respect above requirements

sudo sed '/server_name _;/a\location /redirect_me { return 301 http://www.google.com; }' /etc/nginx/nginx.conf
