#!/usr/bin/env bash
# This script automatically configure a Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
string="server_name _;\n\trewrite ^\/redirect_me http:\/\/google.com permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

string2="server_name _;\n\troot /var/www/html/;\n\tadd_header X-Served-By $host_name;"
sudo sed -i "s/server_name _;/$string2/" /etc/nginx/sites-enabled/default
sudo service nginx restart
